# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.7
_src_path: gh:algorandfoundation/algokit-python-template
author_email: ixondev@gmail.com
author_name: ixondev
contract_name: digital_marketplace
deployment_language: python
preset_name: production
project_name: digital_marketplace

