# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.4
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: ixondev@gmail.com
author_name: ixondev
cloud_provider: none
preset_name: production
project_name: frontend

